/* Generated by Yosys 0.19+36 (git sha1 a207fd4b335, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_3bit_rc(clk, ori, count);
  input clk;
  wire clk;
  output [2:0] count;
  wire [2:0] count;
  input ori;
  wire ori;
  reg [2:0] temp;
  always @(posedge clk, posedge ori)
    if (ori) temp[0] <= 1'h0;
    else temp[0] <= temp[1];
  always @(posedge clk, posedge ori)
    if (ori) temp[1] <= 1'h0;
    else temp[1] <= temp[2];
  always @(posedge clk, posedge ori)
    if (ori) temp[2] <= 1'h1;
    else temp[2] <= temp[0];
  assign count = temp;
endmodule
